INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('100', 'F100', '100', 30, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('141', 'B461', '146-100 Pax', 11, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('142', 'B462', '146-200 Pax', 11, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('143', 'B463', '146-300 Pax', 11, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('146', '', '146 all pax models', 11, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('310', 'A310', 'A310 all pax models', 6, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('312', 'A310', 'A310-200 pax', 6, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('313', 'A310', 'A310-300 pax', 6, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('318', 'A318', 'A318', 6, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('319', 'A319', 'A319', 6, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('320', 'A320', 'A320-100/200', 6, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('321', 'A321', 'A321-100/200', 6, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('330', 'A330', 'A330 all models', 6, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('332', 'A332', 'A330-200', 6, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('333', 'A333', 'A330-300', 6, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('340', 'A340', 'A340 all models', 6, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('342', 'A342', 'A340-200', 6, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('343', 'A343', 'A340-300', 6, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('345', 'A345', 'A340-500', 6, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('346', 'A346', 'A340-600', 6, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('380', '', 'A380 pax', 6, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('703', 'B703', '707-300 pax', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('707', '', '707/720 all pax models', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('717', 'B712', '717', 14, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('721', 'B721', '727-100 pax', 14, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('722', 'B722', '727-200 pax', 14, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('727', '', '727 all pax models', 14, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('731', 'B731', '737-100 pax', 14, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('732', 'B732', '737-200 pax', 14, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('733', 'B733', '737-300 pax', 14, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('734', 'B734', '737-400 pax', 14, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('735', 'B734', '737-500 pax', 14, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('736', 'B736', '737-600 pax', 14, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('737', '', '737 all pax models', 14, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('738', 'B738', '737-800 pax', 14, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('739', 'B739', '737-900 pax', 14, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('741', 'B741', '747-100 pax', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('742', 'B742', '747-200 pax', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('743', 'B743', '747-300 pax', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('744', 'B744', '747-400 pax', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('747', '', '747 all pax models', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('752', 'B752', '757-200 pax', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('753', 'B753', '757-300 pax', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('757', '', '757 all pax models', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('762', 'B762', '767-200 pax', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('763', 'B763', '767-300 pax', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('764', 'B764', '767-400 pax', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('767', '', '767 all pax models', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('772', 'B772', '777-200 pax', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('773', 'B773', '777-300 pax', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('777', '', '777 all pax models', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('14F', '', '146 Freighter (-100/200/300QT & QC)', 11, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('14X', 'B461', '146 Freighter (-100QT & QC)', 11, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('14Y', 'B462', '146 Freighter (-200QT & QC)', 11, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('14Z', 'B463', '146 Freighter (-200QT & QC)', 11, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('31F', 'A310', 'A310 Freighter', 6, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('31X', 'A310', 'A310-200 Freighter', 6, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('31Y', 'A310', 'A310-300 Freighter', 6, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('32S', '', 'A318/319/320/321', 6, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('38F', '', 'A380 Freighter', 6, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('70F', 'B703', '707 Freighter', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('70M', 'B703', '707 Combi', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('72B', 'B721', '727-100 Mixed Configuration', 14, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('72C', 'B722', '727-200 Mixed Configuration', 14, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('72F', '', '727 Freighter (-100/200)', 14, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('72M', '', '727 Combi', 14, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('72S', 'B722', '727-200 Advanced pax', 14, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('72X', 'B721', '727-100 Freighter', 14, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('72Y', 'B722', '727-200 Freighter', 14, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('73F', '', '737 all Freighter models', 14, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('73G', 'B737', '737-700 pax', 14, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('73H', 'B738', '737-800 (winglets) pax', 14, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('73M', 'B732', '737-200 Combi', 14, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('73W', 'B737', '737-700 (winglets) pax', 14, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('73X', 'B732', '737-200 Freighter', 14, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('73Y', 'B733', '737-300 Freighter', 14, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('74C', 'B742', '747-200 Combi', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('74D', 'B743', '747-300 Combi', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('74E', 'B744', '747-400 Combi', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('74F', '', '747 all Freighter models', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('74J', 'B744', '747-400 (Domestic) pax', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('74L', 'N74S', '747SP', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('74M', '', '747 all Combi models', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('74R', 'B74R', '747SR pax', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('74T', 'B741', '747-100 Freighter', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('74U', 'B743', '747-300 / 747-200 SUD Freighter', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('74V', 'B74R', '747SR Freighter', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('74X', 'B742', '747-200 Freighter', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('74Y', 'B744', '747-400 Freighter', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('75F', 'B752', '757 Freighter', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('75M', 'B752', '757 Mixed Configuration', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('76F', '', '767 all Freighter models', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('76X', 'B762', '767-200 Freighter', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('76Y', 'B763', '767-300 Freighter', 14, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('A26', 'AN26', 'AN-26', 8, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('A28', 'AN28', 'AN-28 / PZL Miele M-28 Skytruck', 8, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('A30', 'AN30', 'AN-30', 8, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('A32', 'AN32', 'AN-32', 8, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('A40', 'A140', 'AN-140', 8, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('A4F', 'A124', 'AN-124 Ruslan', 8, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('AB3', 'A30B', 'A300 pax', 7, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('AB4', 'A30B', 'A300B2/B4/C4 pax', 7, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('AB6', 'A306', 'A300-600 pax', 7, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('ABB', 'A3ST', 'A300-600ST Beluga Freighter', 7, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('ABF', 'A30B', 'A300 Freighter', 7, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('ABX', 'A30B', 'A300C4/F4 Freighter', 7, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('ABY', 'A306', 'A600-600 Freighter', 7, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('ACD', '', '(Aero) Commander/Turbo Commander', 35, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('ACP', 'AC68', '(Aero) Commander', 35, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('ACT', 'AC90', '(Aero) Turbo Commander', 35, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('ALM', 'LOAD', 'LM-200 Loadmaster', 10, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('AN4', 'AN24', 'AN-24', 8, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('AN6', '', 'AN-26 / AN-30 /AN-32', 8, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('AN7', 'AN72', 'AN-72 / AN-74', 8, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('ANF', 'AN12', 'AN-12', 8, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('APH', '', 'SA330 Puma / AS332 Super Puma', 27, NULL);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('AR1', 'RJ1H', 'RJ100 Avroliner', 9, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('AR7', 'RJ70', 'RJ70 Avroliner', 9, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('AR8', 'RJ85', 'RJ85 Avroliner', 9, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('ARJ', '', 'RJ70 / RJ85 / RJ100 Avroliner', 9, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('ARX', '', 'RJX85 / RJX100', 9, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('AT4', 'AT43', 'ATR 42-300 / 320', 4, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('AT5', 'AT45', 'ATR 42-500', 4, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('AT7', 'AT72', 'ATR 72', 4, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('ATP', 'ATP', 'ATP', 15, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('ATR', '', 'ATR 42/ ATR 72', 4, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('AX1', 'RX1H', 'RJX100', 9, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('AX8', 'RX85', 'RJX85', 9, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('B11', 'BA11', '(BAC) One Eleven / RomBAC One Eleven', 15, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('B12', 'BA11', '(BAC) One Eleven 200', 15, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('B13', 'BA11', '(BAC) One Eleven 300', 15, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('B14', 'BA11', '(BAC) One Eleven 400/475', 15, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('B15', 'BA11', '(BAC) One Eleven 500 / RomBAC One Eleven', 15, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('B72', 'B720', '720B pax', 14, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('BE1', 'B190', '1900/1900C/1900D', 12, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('BE2', '', 'twin piston engines', 12, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('BEC', '', 'light aircraft', 12, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('BEH', 'B190', '1900D', 12, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('BEP', '', 'light aircraft – single engine', 12, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('BES', 'B190', '1900/1900C', 12, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('BET', '', 'light aircraft – twin turboprop engine', 12, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('BH2', '', '', 13, NULL);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('BNI', 'BN2P', 'Britten-Norman BN-2A/B Islander', 51, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('BNT', 'TRIS', 'Britten-Norman BN-2A Mk III Trislander', 51, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('CCJ', 'CL60', 'Challenger', 17, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('CCX', 'GLEX', 'Global Express', 17, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('CD2', 'NOMA', 'N22B / N24A Nomad', 32, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('CL4', 'CL44', 'CL-44', 17, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('CN1', '', 'light aircraft – single piston engine', 19, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('CN2', '', 'light aircraft – twin piston engines', 19, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('CNA', '', 'light aircraft', 19, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('CNC', '', 'light aircraft – single turboprop engine', 19, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('CNJ', '', 'Citation', 19, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('CNT', '', 'light aircraft – twin turboprop engines', 19, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('CR1', 'CRJ1', 'Regional Jet 100', 17, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('CR2', 'CRJ2', 'Regional Jet 200', 17, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('CR7', 'CRJ7', 'Regional Jet 700', 17, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('CR9', 'CRJ9', 'Regional Jet 900', 17, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('CRJ', '', 'Regional Jet', 17, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('CRV', 'S210', 'Se.210 Caravelle', 3, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('CS2', 'C212', '212 Aviocar', 18, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('CS5', 'CN35', 'CN-235', 18, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('CV4', 'CVLP', 'CV-440 Metropolitan pax', 20, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('CV5', 'CVLT', 'CV-580 pax', 20, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('CVF', '', 'CV-240 / 440 / 580 / 600 / 640 Freighter', 20, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('CVR', '', 'CV-240 / 440 / 580 / 600 / 640 pax', 20, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('CVV', 'CVLP', 'CV-240 Freighter', 20, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('CVX', 'CVLP', 'CV-440 Freighter', 20, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('CVY', 'CVLT', 'CV-580 / 600 / 640 Freighter', 20, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('CWC', 'C46', 'C-46 Commando', 21, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('D10', 'DC10', 'DC-10 pax', 24, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('D11', 'DC10', 'DC-10-10/15 pax', 24, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('D1C', 'DC10', 'DC-10-30/40 pax', 24, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('D1F', 'DC10', 'DC-10 all Freighters', 24, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('D1M', 'DC10', 'DC-10 all Combi models', 24, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('D1X', 'DC10', 'DC-10-10 Freighter', 24, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('D1Y', 'DC10', 'DC-10-30 / 40 Freighters', 24, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('D28', 'D228', 'Dornier Do.228', 28, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('D38', 'D328', 'Dornier Do.328', 28, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('D3F', 'DC3', 'DC-3 Freighter', 24, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('D6F', 'DC6', 'DC-6A/B/C Freighter', 24, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('D8F', '', 'DC-8 all Freighters', 24, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('D8L', 'DC86', 'DC-8-62 pax', 24, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('D8M', '', 'DC-8 all Combi models', 24, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('D8Q', 'DC87', 'DC-8-72 pax', 24, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('D8T', 'DC85', 'DC-8-50 Freighter', 24, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('D8X', '', 'DC-8-61 / 62 / 63 Freighters', 24, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('D8Y', 'DC87', 'DC-8-71 / 72 / 73 Freighters', 24, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('D91', 'DC91', 'DC-9-10 pax', 24, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('D92', 'DC92', 'DC-9-20 pax', 24, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('D93', 'DC93', 'DC-9-30 pax', 24, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('D94', 'DC94', 'DC-9-40 pax', 24, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('D95', 'DC95', 'DC-9-50 pax', 24, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('D9C', 'DC93', 'DC-9-30 Freighter', 24, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('D9F', '', 'DC-9 all Freighters', 24, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('D9F', 'DC94', 'DC-9-40 Freighter', 24, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('D9X', 'DC91', 'DC-9-10 Freighter', 24, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('DC3', 'DC3', 'DC-3 pax', 24, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('DC6', 'DC6', 'DC6A/B pax', 24, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('DC8', '', 'DC-8 all pax models', 24, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('DC9', 'DC9', 'DC-9 all pax models', 24, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('DF2', '', '(Breguet Mystere) Falcon 10 / 100 / 20 / 200 / 2000', 22, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('DF3', '', '(Breguet Mystere) Falcon 50 / 900', 22, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('DFL', '', '(Breguet Mystere) Falcon', 22, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('DH1', 'DH8A', 'Canada DHC-8-100 Dash 8 / 8Q', 23, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('DH2', 'DH8B', 'Canada DHC-8-200 Dash 8 / 8Q', 23, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('DH3', 'DH8C', 'Canada DHC-8-300 Dash 8 / 8Q', 23, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('DH4', 'DH8D', 'Canada DHC-8-400 Dash 8Q', 23, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('DH7', 'DHC7', 'Canada DHC-7 Dash 7', 23, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('DH8', '', 'Canada DHC-8 Dash 8 all models', 23, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('DHB', '', 'Canada DHC-2 Beaver / Turbo Beaver', 23, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('DHC', 'DHC4', 'Canada DHC-4 Caribou', 23, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('DHD', 'DOVE', 'DH.104 Dove', 23, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('DHH', 'HERN', 'DH.114 Heron', 23, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('DHL', 'DHC3', 'Canada DHC-3 Turbo Otter', 23, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('DHO', 'DHC3', 'Canada DHC-3 Otter / Turbo Otter', 23, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('DHP', 'DHC2', 'Canada DHC-2 Beaver', 23, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('DHR', 'DH2T', 'Canada DHC-2 Turbo-Beaver', 23, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('DHS', 'DHC3', 'Canada DHC-3 Otter', 23, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('DHT', 'DHC6', 'Canada DHC-6 Twin Otter', 23, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('E70', 'E170', '170', 25, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('E90', 'E190', '190', 25, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('EM2', 'E120', 'EMB.120 Brasilia', 25, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('EMB', 'E110', 'EMB.110 Bandeirnate', 25, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('EMJ', '', '170/190', 25, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('ER3', 'E135', 'RJ135', 25, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('ER4', 'E145', 'RJ145 Amazon', 25, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('ERD', '', 'RJ140', 25, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('ERJ', '', 'RJ135 / RJ140 / RJ145', 25, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('F21', 'F28', 'F.28 Fellowship 1000', 30, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('F22', 'F28', 'F.28 Fellowship 2000', 30, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('F23', 'F28', 'F.28 Fellowship 3000', 30, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('F24', 'F28', 'F.28 Fellowship 4000', 30, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('F27', 'F27', 'F.27 Friendship / Fairchild F.27', 30, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('F28', 'F28', 'F.28 Fellowship', 30, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('F50', 'F50', '50', 30, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('F70', 'F70', '70', 30, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('FA7', '', 'Dornier 728JET', 28, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('FK7', 'F27', 'FH.227', 28, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('FRJ', 'J328', 'Dornier 328JET', 28, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('GRG', 'G21', 'G.21 Goose', 33, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('GRJ', '', 'G-1159 Gulfstream II / III / IV / V', 34, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('GRM', 'G73T', 'G.73 Turbo Mallard', 33, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('GRS', 'G159', 'G-159 Gulfstream I', 34, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('H25', '', 'HS.125', 16, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('HEC', 'COUC', 'H-250 Courier / H-295 / 385 Super Courier', 38, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('HOV', '', '', 39, NULL);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('HS7', 'A748', 'HS.748', 37, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('I14', 'I114', 'IL114', 40, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('I93', 'IL96', 'IL96-300 pax', 40, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('I9F', 'IL96', 'IL96 Freighters', 40, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('I9M', 'IL96', 'IL96M pax', 40, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('I9X', 'IL96', 'IL96-300 Freighter', 40, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('I9Y', 'IL96', 'IL96T Freighter', 40, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('IL6', 'IL62', 'IL62', 40, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('IL7', 'IL76', 'IL76', 40, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('IL8', 'IL18', 'IL18', 40, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('IL9', 'IL96', 'IL96 pax', 40, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('ILW', 'IL86', 'IL86', 40, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('J31', 'JS31', 'Jetstream 31', 15, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('J32', 'JS32', 'Jetstream 32', 15, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('J41', 'JS41', 'Jetstream 41', 15, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('JST', '', 'Jetstream 31 / 32 / 41', 15, NULL);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('JU5', 'JU52', 'Ju52/3M', 42, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('L10', 'L101', 'L-1011 Tristar pax', 44, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('L11', 'L101', 'L-1011 1 / 50 / 100 / 150 / 200 / 250 Tristar pax', 44, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('L15', 'L101', 'L-1011 500 Tristar pax', 44, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('L1F', 'L101', 'L-1011 Tristar Freighter', 44, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('L49', 'CONI', 'L-1049 Super Constellation', 44, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('L4T', 'L410', '410', 43, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('LOE', 'L188', 'L-188 Electra pax', 44, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('LOF', 'L188', 'L-188 Electra Freighter', 44, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('LOH', 'C130', 'L-182 / 282 / 382 (L-100) Hercules', 44, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('LOM', 'L188', 'L-188 Electra Mixed Configuration', 44, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('LRJ', '', 'Learjet', 31, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('M11', 'MD11', 'MD11 pax', 45, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('M1F', 'MD11', 'MD11 Freighter', 45, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('M1M', 'MD11', 'MD11 Mixed Configuration', 45, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('M80', 'MD80', 'MD80', 45, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('M81', 'MD81', 'MD81', 45, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('M82', 'MD82', 'MD82', 45, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('M83', 'MD83', 'MD83', 45, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('M87', 'MD87', 'MD87', 45, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('M88', 'MD88', 'MD88', 45, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('M90', 'MD90', 'MD90', 45, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('MBH', 'B105', '(MBB) Bo.105', 26, NULL);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('MD9', 'EXPL', 'MD900 Explorer', 46, NULL);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('MIH', 'MI8', 'Mi-8 / Mi-17 / Mi-171 / Mil-172', 47, NULL);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('MU2', 'MU2', 'Mu-2', 48, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('ND2', 'N262', '262', 2, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('NDC', 'S601', 'SN.601 Corvette', 1, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('NDE', '', '(Aerospatiale) AS350 Ecureuil / AS355 Ecureuil 2', 26, NULL);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('NDH', 'S65C', '(Aerospatiale) SA365C / SA365N Dauphin 2', 26, NULL);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('PA1', '', 'light aircraft – single piston engine', 52, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('PA2', '', 'light aircraft – twin piston engines', 52, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('PAG', '', 'light aircraft', 52, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('PAT', '', 'light aircraft – twin turboprop engines', 52, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('PL2', 'PC12', 'PC-12', 51, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('PL6', 'PC6T', 'PC-6 Turbo Porter', 51, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('PN6', 'P68', 'P.68', 50, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('S20', 'SB20', '2000', 53, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('S58', 'S58T', 'S-58T', 55, NULL);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('S61', 'S61', 'S-61', 55, NULL);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('S76', 'S76', 'S-76', 55, NULL);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('SF3', 'SF34', 'SF340A/B', 53, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('SH3', 'SH33', 'SD.330', 54, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('SH6', 'SH36', 'SD.360', 54, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('SHB', 'BELF', 'SC-5 Belfast', 54, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('SHS', 'SC7', 'SC-7 Skyvan', 54, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('SSC', 'CONC', 'Concorde', 5, 1);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('SWM', '', 'SA26 / SA226 / SA227 Metro / Merlin / Expediter', 29, 3);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('T20', 'T204', 'Tu-204 / Tu-214', 56, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('TU3', 'T134', 'Tu134', 56, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('TU5', 'T154', 'Tu154', 56, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('VCV', 'VISC', 'Viscount', 57, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('WWP', 'WW24', '1124 Westwind', 41, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('YK2', 'YK42', 'Yak 42', 59, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('YK4', 'YK40', 'Yak 40', 59, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('YN2', 'Y12', 'Yunshuji Y12', 36, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('YN7', 'AN24', 'Yunshuji Y7', 58, 4);
INSERT INTO AIRCRAFT_MODEL ( IATA, ICAO, Name, ManufacturerId, WakeTurbulenceCategoryId) VALUES ('YS1', 'YS11', 'YS-11', 49, 4);
