INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '1', 'Aerospatiale');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '2', 'Aerospatiale (Nord)');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '3', 'Aerospatiale (Sud Aviation)');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '4', 'Aerospatiale/Alenia');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '5', 'Aerospatiale/BAC');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '6', 'Airbus');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '7', 'Airbus Industrie');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '8', 'Antonov');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '9', 'Avro');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '10', 'Ayres');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '11', 'BAe');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '12', 'Beechcraft');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '13', 'Bell Helicopters');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '14', 'Boeing');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '15', 'British Aerospace');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '16', 'British Aerospace (Hawker Siddeley)');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '17', 'Canadair');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '18', 'CASA / IPTN');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '19', 'Cessna');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '20', 'Convair');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '21', 'Curtiss');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '22', 'Dassault');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '23', 'De Havilland');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '24', 'Douglas');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '25', 'Embraer');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '26', 'Eurocopter');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '27', 'Eurocopter (Aerospatiale)');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '28', 'Fairchild');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '29', 'Fairchild (Swearingen)');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '30', 'Fokker');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '31', 'Gates');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '32', 'Government Aircraft Factories');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '33', 'Grumman');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '34', 'Gulfstream Aerospace');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '35', 'Gulfstream/Rockwell');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '36', 'Harbin');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '37', 'Hawker Siddeley');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '38', 'Helio');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '39', 'Hovercraft');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '40', 'Ilyushin');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '41', 'Israel Aircraft Industries');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '42', 'Junkers');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '43', 'LET');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '44', 'Lockheed');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '45', 'McDonnell Douglas');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '46', 'MD Helicopters');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '47', 'MIL');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '48', 'Mitsubishi');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '49', 'NAMC');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '50', 'Partenavia');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '51', 'Pilatus');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '52', 'Piper');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '53', 'Saab');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '54', 'Shorts');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '55', 'Sikorsky');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '56', 'Tupolev');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '57', 'Vickers');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '58', 'Xian');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '59', 'Yakovlev');
