INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '1', 'Aerospatiale (Nord)');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '2', 'Aerospatiale');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '3', 'Aerospatiale/Alenia');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '4', 'Airbus');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '5', 'Antonov');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '6', 'Avro');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '7', 'BAe');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '8', 'Beechraft');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '9', 'Bell');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '10', 'Beriev');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '11', 'Boeing');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '12', 'Bombardier');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '13', 'Bombardier Global Express');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '14', 'British Aerospace');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '15', 'Canadair');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '16', 'CASA/IPTN');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '17', 'Cessna');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '18', 'Cirrus');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '19', 'COMARC');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '20', 'Convair');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '21', 'Curtiss');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '22', 'Daher');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '23', 'Dassault');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '24', 'De Havilland');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '25', 'Diamond');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '26', 'Dornier');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '27', 'Douglas');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '28', 'Eclipse');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '29', 'Embraer');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '30', 'Eurocopter (Aerospatiale)');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '31', 'Eurocopter');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '32', 'Fairchild Dornier');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '33', 'Fairchild Swearingen');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '34', 'Fokker');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '35', 'Government Aircraft Factories');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '36', 'Grumman');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '37', 'Gulfstream Aerospace');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '38', 'Gulfstream');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '39', 'Gulfstream/Rockwell ');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '40', 'Harbin');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '41', 'Hawker');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '42', 'Hawker Siddeley');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '43', 'Honda');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '44', 'Ilyushin');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '45', 'Israel Aircraft Industries');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '46', 'Junkers');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '47', 'Learjet');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '48', 'LET');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '49', 'Lockheed');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '50', 'Lockheed Martin');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '51', 'McDonnell Douglas');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '52', 'MD Helicopters');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '53', 'MIL');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '54', 'Mitsubishi');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '55', 'NAMC');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '56', 'Patrenavia');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '57', 'Piaggio');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '58', 'Pilatus');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '59', 'Piper');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '60', 'Reims-Cessna');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '61', 'Saab');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '62', 'Shorts');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '63', 'Sikorsky');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '64', 'Sukhoi');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '65', 'Tecnam');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '66', 'Tupolev');
INSERT INTO MANUFACTURER ( Id, Name ) VALUES ( '67', 'Yakovlev');
