INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('ND2', 'N262', '262', 1);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('NDC', 'S601', 'SN.601 Corvette', 2);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('AT4', 'AT43', 'ATR 42-300 / 320', 3);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('AT5', 'AT45', 'ATR 42-500', 3);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('ATR', 'AT46', 'ATR 42-600', 3);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('AT7', 'AT72', 'ATR 72-201/-202', 3);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('ATR', 'AT73', 'ATR 72-211/-212', 3);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('ATR', 'AT75', 'ATR 72-212A (500)', 3);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('ATR', 'AT76', 'ATR 72-212A (600)', 3);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('221', 'BCS1', 'A220-100', 4);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('223', 'BCS3', 'A220-300', 4);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('AB6', 'A306', 'A300-600', 4);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('ABY', 'A306', 'A300-600 Freighter', 4);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('ABB', 'A3ST', 'A300-600ST "Super Transporter" / "Beluga"', 4);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('AB4', 'A30B', 'A300B2, A300B4, and A300C4', 4);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('312', 'A310', 'A310-200', 4);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('313', 'A310', 'A310-300', 4);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('318', 'A318', 'A318', 4);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('32C', 'A318', 'A318 (sharklets)', 4);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('319', 'A319', 'A319', 4);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('32D', 'A319', 'A319 (sharklets)', 4);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('31N', 'A19N', 'A319neo', 4);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('320', 'A320', 'A320', 4);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('32A', 'A320', 'A320 (sharklets)', 4);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('32N', 'A20N', 'A320neo', 4);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('321', 'A321', 'A321', 4);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('32B', 'A321', 'A321 (sharklets)', 4);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('32Q', 'A21N', 'A321neo', 4);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('332', 'A332', 'A330-200', 4);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('33X', 'A332', 'A330-200 Freighter', 4);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('333', 'A333', 'A330-300', 4);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('33Y', 'A333', 'A330-300 Freighter', 4);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'A337', 'A330-700 "BelugaXL"', 4);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('338', 'A338', 'A330-800', 4);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('339', 'A339', 'A330-900', 4);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('342', 'A342', 'A340-200', 4);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('343', 'A343', 'A340-300', 4);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('345', 'A345', 'A340-500', 4);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('346', 'A346', 'A340-600', 4);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('351', 'A35K', 'A350-1000', 4);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('359', 'A359', 'A350-900', 4);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('388', 'A388', 'A380-800', 4);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'A400', 'A400M Atlas', 4);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('ANF', 'AN12', 'An-12', 5);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('A4F', 'A124', 'An-124 Ruslan', 5);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('A40', 'A140', 'An-140', 5);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('A81', 'A148', 'An-148', 5);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('A58', 'A158', 'An-158', 5);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('A5F', 'A225', 'An-225 Mriya', 5);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('AN4', 'AN24', 'An-24', 5);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('A26', 'AN26', 'An-26', 5);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('A28', 'AN28', 'An-28', 5);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('A30', 'AN30', 'An-30', 5);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('A32', 'AN32', 'An-32', 5);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('AN7', 'AN72', 'An-72 / An-74', 5);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('AR1', 'RJ1H', 'RJ100', 6);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('AR7', 'RJ70', 'RJ70', 6);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('AR8', 'RJ85', 'RJ85', 6);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('141', 'B461', '146-100 / Avro RJ70', 7);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('142', 'B462', '146-200 / Avro RJ85', 7);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('143', 'B463', '146-300 / Avro RJ100', 7);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'BE20', 't (Super) King Air 200', 8);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('BEH', 'B190', 't 1900', 8);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'BE55', 't 55 Baron', 8);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'BE58', 't 58 Baron', 8);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'BE76', 't Model 76 Duchess', 8);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'BE99', 't Model 99', 8);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'B06', '206 JetRanger', 9);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'B06T', '206 TwinRanger', 9);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('BH2', 'B212', '212', 9);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('BH2', 'B412', '412', 9);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('BH2', 'B429', '429', 9);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'V22', 'Boeing V-22 Osprey', 9);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'BER2', 'Be-200 Altair', 10);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('703', 'B703', '707', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('717', 'B712', '717', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('B72', 'B720', '720B', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('721', 'B721', '727-100', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('722', 'B722', '727-200', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('7MJ', 'B3XM', '737 MAX 10', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('7M7', 'B37M', '737 MAX 7', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('7M8', 'B38M', '737 MAX 8', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('7M9', 'B39M', '737 MAX 9', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('732', 'B732', '737-200', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('73F', 'B732', '737-200 Freighter', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('733', 'B733', '737-300', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('73Y', 'B733', '737-300 Freighter', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('73C', 'B733', '737-300 Winglets', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('734', 'B734', '737-400', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('73P', 'B734', '737-400 Freighter', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('735', 'B735', '737-500', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('73E', 'B735', '737-500 Winglets', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('736', 'B736', '737-600', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('73G', 'B737', '737-700 / Boeing 737-700ER', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('73W', 'B737', '737-700 Winglets', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('738', 'B738', '737-800', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('73U', 'B738', '737-800 Freighter', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('73K', 'B738', '737-800 Freighter Winglets', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('73H', 'B738', '737-800 Winglets', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('739', 'B739', '737-900 / Boeing 737-900ER', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('73J', 'B739', '737-900 Winglets', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('74B', 'BLCF', '747 LCF Dreamlifter', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('741', 'B741', '747-100', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('74T', 'B741', '747-100 Freighter', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('742', 'B742', '747-200', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('74X', 'B742', '747-200F', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('74C', 'B742', '747-200M', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('743', 'B743', '747-300', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('74D', 'B743', '747-300M', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('744', 'B744', '747-400 / Boeing 747-400ER', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('74Y', 'B744', '747-400F / Boeing 747-400ERF', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('74E', 'B744', '747-400M', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('74N', 'B748', '747-8F', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('74H', 'B748', '747-8I', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('74L', 'B74S', '747SP', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('74R', 'B74R', '747SR', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('74V', 'B74R', '747SR Freighter', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('752', 'B752', '757-200', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('753', 'B753', '757-300', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('75F', 'B752', '757F', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('762', 'B762', '767-200 / Boeing 767-200ER', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('76X', 'B762', '767-200 Freighter / Boeing 767-200ER', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('763', 'B763', '767-300', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('76Y', 'B763', '767-300 Freighter', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('76W', 'B763', '767-300 Winglets / Boeing 767-300ER', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('764', 'B764', '767-400ER', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('772', 'B772', '777-200 / Boeing 777-200ER', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('77X', 'B77L', '777-200 Freighter', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('77L', 'B77L', '777-200LR', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('773', 'B773', '777-300', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('77W', 'B77W', '777-300ER', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('778', 'B778', '777-8', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('779', 'B779', '777-9', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('781', 'B78X', '787-10', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('788', 'B788', '787-8', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('789', 'B789', '787-9', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('N/A', 'B52', 'B-52 Stratofortress', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('K35', 'K35R', 'KC-135 Stratotanker', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'P8', 'P-8 Poseidon', 11);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'CL2T', '415', 12);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'CL30', 'BD-100 Challenger 300', 12);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('CCX', 'GL5T', 'BD-700 Global 5000', 12);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('CCX', 'GLEX', 'Raytheon Sentinel', 13);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('B11', 'BA11', '(BAC) One Eleven', 14);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('H25', 'H25B', '125 series / Hawker/Raytheon 700/800/800XP/850/900', 14);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('H25', 'H25C', '125-1000 series / Hawker/Raytheon 1000', 14);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('ATP', 'ATP', 'ATP', 14);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('J31', 'JS31', 'Jetstream 31', 14);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('J32', 'JS32', 'Jetstream 32', 14);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('J41', 'JS41', 'Jetstream 41', 14);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('CCJ', 'CL60', 'Challenger 600', 15);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('CR1', 'CRJ1', 'Regional Jet 100', 15);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('CRK', 'CRJX', 'Regional Jet 1000', 15);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('CR2', 'CRJ2', 'Regional Jet 200', 15);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('CR7', 'CRJ7', 'Regional Jet 700 | Regional Jet 550', 15);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('CR9', 'CRJ9', 'Regional Jet 900', 15);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('CS2', 'C212', '212 Aviocar', 16);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('CS5', 'CN35', 'CN-235', 16);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('CN1', 'C208', '208 Caravan', 17);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'C310', '310', 17);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('CNJ', 'C25A', 'Citation CJ2', 17);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('CNJ', 'C25B', 'Citation CJ3', 17);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('CNJ', 'C25C', 'Citation CJ4', 17);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('CNJ', 'C56X', 'Citation Excel', 17);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('CNJ', 'C500', 'Citation I', 17);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('CNJ', 'C550', 'Citation II', 17);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('CNJ', 'C650', 'Citation III, VI, VII', 17);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('CNJ', 'C700', 'Citation Longitude', 17);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('CNJ', 'C510', 'Citation Mustang', 17);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('CNJ', 'C680', 'Citation Sovereign', 17);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('CNJ', 'C560', 'Citation V', 17);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('CNJ', 'C750', 'Citation X', 17);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('CNJ', 'C525', 'CitationJet', 17);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'SF50', 'SF50 Vision Jet', 18);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('C27', 'AJ27', 'ARJ21', 19);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('919', 'C919', 'C919', 19);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('CV4', 'CVLP', 'CV-240 & -440', 20);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('CV5', 'CVLT', 'CV-580, Convair CV-600, Convair CV-640', 20);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('CWC', 'C46', 'C-46 Commando', 21);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'TBM7', 'TBM 700', 22);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'TBM8', 'TBM 850', 22);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'TBM9', 'TBM 900', 22);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'TBM9', 'TBM 910', 22);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'TBM9', 'TBM 930', 22);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'TBM9', 'TBM 940', 22);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'TBM9', 'TBM 960', 22);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('D20', 'F2TH', 'Falcon 2000', 23);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('DF3', 'FA50', 'Falcon 50', 23);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('DF7', 'FA7X', 'Falcon 7X', 23);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('DF9', 'F900', 'Falcon 900', 23);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('DHR', 'DH2T', 'Canada DHC-2 Turbo-Beaver', 24);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('DHC', 'DHC4', 'Canada DHC-4 Caribou', 24);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('DHC', 'DHC5', 'Canada DHC-5 Buffalo', 24);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('DHT', 'DHC6', 'Canada DHC-6 Twin Otter', 24);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('DH7', 'DHC7', 'Canada DHC-7 Dash 7', 24);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('DH1', 'DH8A', 'Canada DHC-8-100 Dash 8 / 8Q', 24);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('DH2', 'DH8B', 'Canada DHC-8-200 Dash 8 / 8Q', 24);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('DH3', 'DH8C', 'Canada DHC-8-300 Dash 8 / 8Q', 24);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('DH4', 'DH8D', 'Canada DHC-8-400 Dash 8Q', 24);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('DHD', 'DOVE', 'DH.104 Dove', 24);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('DHH', 'HERN', 'DH.114 Heron', 24);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'DA42', 'DA42', 25);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'DA62', 'DA62', 25);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('D28', 'D228', '228', 26);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('D11', 'DC10', 'DC-10-10 / -15 Passenger', 27);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('D1X', 'DC10', 'DC-10-10 Freighter', 27);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('D1Y', 'DC10', 'DC-10-30 / -40 Freighter', 27);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('D1C', 'DC10', 'DC-10-30 / -40 Passenger', 27);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('D1M', 'DC10', 'DC-10-30 Combi', 27);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('D3F', 'DC3', 'DC-3', 27);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('D6F', 'DC6', 'DC-6', 27);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('D8T', 'DC85', 'DC-8-50', 27);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('D8L', 'DC86', 'DC-8-62', 27);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('D8Q', 'DC87', 'DC-8-72', 27);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('D91', 'DC91', 'DC-9-10', 27);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('D92', 'DC92', 'DC-9-20', 27);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('D93', 'DC93', 'DC-9-30', 27);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('D94', 'DC94', 'DC-9-40', 27);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('D95', 'DC95', 'DC-9-50', 27);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'EA50', '500', 28);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('E70', 'E170', '170', 29);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('E7W', 'E75L', '175 (long wing)', 29);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('E75', 'E75S', '175 (short wing)', 29);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('E90', 'E190', '190 / Lineage 1000', 29);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('E95', 'E195', '195', 29);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('290', 'E290', 'E190-E2', 29);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('295', 'E295', 'E195-E2', 29);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('EMB', 'E110', 'EMB 110 Bandeirante', 29);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('EM2', 'E120', 'EMB 120 Brasilia', 29);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'E545', 'Legacy 450 / Praetor 500', 29);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'E550', 'Legacy 500 / Praetor 600', 29);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('ER3', 'E35L', 'Legacy 600 / Legacy 650', 29);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('EP1', 'E50P', 'Phenom 100', 29);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('EP3', 'E55P', 'Phenom 300', 29);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('ER3', 'E135', 'RJ135', 29);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('ERD', 'E135', 'RJ140', 29);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('ER4', 'E145', 'RJ145', 29);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('NDH', 'S65C', 'SA365C Dauphin 2', 30);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('MBH', 'B105', '(MBB) Bo.105', 31);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('APH', 'AS32', 'AS332 Super Puma', 31);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('NDE', 'AS50', 'AS350 cureuil / AS550 Fennec', 31);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'EC20', 'EC120 Colibri / Harbin HC120', 31);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'EC30', 'EC130', 31);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'EC35', 'EC135 / EC635', 31);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'EC45', 'EC145', 31);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'EC55', 'EC155', 31);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'EC75', 'EC175', 31);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'EC25', 'EC225 Super Puma', 31);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('FRJ', 'J328', '328JET', 32);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('D38', 'D328', 'Do.328', 32);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('SW4', 'SW4', 'Metroliner', 33);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('100', 'F100', '100', 34);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('F50', 'F50', '50', 34);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('F70', 'F70', '70', 34);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('F27', 'F27', 'F27 Friendship', 34);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('F21', 'F28', 'F28 Fellowship', 34);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('CD2', 'NOMA', 'N22B / N24A Nomad', 35);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('GRG', 'G21', 'G-21 Goose', 36);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('GRM', 'G73T', 'G-73 Turbo Mallard', 36);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('GRS', 'G159', 'G-159 Gulfstream I', 37);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('GR3', 'G280', 'G280', 38);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('GJ6', 'GLF6', 'G650', 38);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('GJ4', 'GLF4', 'IV', 38);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('GJ5', 'GLF5', 'V', 38);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('ACP', 'AC68', '(Aero) Commander 680', 39);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('ACT', 'AC90', '(Aero) Turbo Commander 690', 39);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('YN2', 'Y12', 'Y-12', 40);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'BE40', '400', 41);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('HS7', 'A748', 'HS 748', 42);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('HHJ', 'HDJT', 'HA-420', 43);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('I14', 'I114', 'Il-114', 44);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('IL8', 'IL18', 'Il-18', 44);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('IL6', 'IL62', 'Il-62', 44);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('IL7', 'IL76', 'Il-76', 44);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('ILW', 'IL86', 'Il-86', 44);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('I93', 'IL96', 'Il-96', 44);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('WWP', 'WW24', '1124 Westwind', 45);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('JU5', 'JU52', 'Ju 52/3M', 46);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('LRJ', 'LJ35', '35 / 36 / C-21A', 47);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('LRJ', 'LJ60', '60', 47);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('L4T', 'L410', '410', 48);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('N/A', 'C5M', 'C-5M Super Galaxy', 49);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('L10', 'L101', 'L-1011 Tristar', 49);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('L49', 'CONI', 'L-1049 Super Constellation', 49);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('LOH', 'C130', 'L-182 / 282 / 382 (L-100) Hercules', 49);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('LOE', 'L188', 'L-188 Electra', 49);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('LOH', 'C30J', 'C-130J Hercules', 50);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('M11', 'MD11', 'MD-11', 51);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('M1M', 'MD11', 'MD-11C', 51);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('M1F', 'MD11', 'MD-11F', 51);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('M81', 'MD81', 'MD-81', 51);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('M82', 'MD82', 'MD-82', 51);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('M83', 'MD83', 'MD-83', 51);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('M87', 'MD87', 'MD-87', 51);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('M88', 'MD88', 'MD-88', 51);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('M90', 'MD90', 'MD-90', 51);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('MD9', 'EXPL', 'MD900 Explorer', 52);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'MI24', 'Mi-24 / Mi-25 / Mi-35', 53);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('MIH', 'MI8', 'Mi-8 / Mi-17 / Mi-171 / Mil-172', 53);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('MU2', 'MU2', 'Mu-2', 54);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('YS1', 'YS11', 'YS-11', 55);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('PN6', 'P68', 'P.68', 56);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('P18', 'P180', 'P.180 Avanti', 57);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('BNT', 'TRIS', 'Britten-Norman BN-2A Mk III Trislander', 58);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('BNI', 'BN2P', 'Britten-Norman BN-2A/B Islander', 58);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('PL2', 'PC12', 'PC-12', 58);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('PL4', 'PC24', 'PC-24', 58);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('PL6', 'PC6T', 'PC-6 Turbo Porter', 58);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('PA2', 'PA31', 'PA-31 Navajo', 59);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'PA34', 'PA-34 Seneca', 59);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'PA44', 'PA-44 Seminole', 59);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('CNT', 'F406', 'F406 Caravan II', 60);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('S20', 'SB20', '2000', 61);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('SF3', 'SF34', 'SF340A/B', 61);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('SHB', 'BELF', 'SC-5 Belfast', 62);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('SHS', 'SC7', 'SC-7 Skyvan', 62);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('SH3', 'SH33', 'SD.330', 62);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('SH6', 'SH36', 'SD.360', 62);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('S58', 'S58T', 'S-58T', 63);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('S61', 'S61', 'S-61', 63);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('S76', 'S76', 'S-76', 63);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('S92', 'S92', 'S-92', 63);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('SU9', 'SU95', 'Superjet 100-95', 64);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('', 'P06T', 'P2006T', 65);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('T12', 'P212', 'P2012 Traveller', 65);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('TU3', 'T134', 'Tu-134', 66);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('TU5', 'T154', 'Tu-154', 66);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('T20', 'T204', 'Tu-204 / Tu-214', 66);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('YK4', 'YK40', 'Yak-40', 67);
INSERT INTO MODEL ( IATA, ICAO, Name, ManufacturerId) VALUES ('YK2', 'YK42', 'Yak-42', 67);
