DROP TABLE IF EXISTS OBSERVED_FLIGHT;

CREATE TABLE OBSERVED_FLIGHT (
    Id      INTEGER NOT NULL CONSTRAINT PK_FLIGHT PRIMARY KEY AUTOINCREMENT,
    Number  TEXT    NOT NULL );

-- Add INSERT statements here
