DELETE FROM POSITION
WHERE AircraftId IN (
    SELECT  Id
    FROM    TRACKED_AIRCRAFT
    WHERE   SessionId < 20
    OR      SessionId IS NULL);

DELETE FROM TRACKED_AIRCRAFT
WHERE       SessionId < 20
OR          SessionId IS NULL

DELETE FROM SESSION
WHERE       Id < 20;
