// <auto-generated />
using System;
using BaseStationReader.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaseStationReader.Data.Migrations
{
    [DbContext(typeof(BaseStationReaderDbContext))]
    [Migration("20260902202852_AddAirlineCallsignPrefixes")]
    partial class AddAirlineCallsignPrefixes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("BaseStationReader.Entities.Api.Aircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Address");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Age");

                    b.Property<int?>("Manufactured")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Manufactured");

                    b.Property<int>("ModelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProvenanceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProvenanceId");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Registration");

                    b.HasKey("Id");

                    b.HasIndex("Address");

                    b.HasIndex("ModelId");

                    b.HasIndex("ProvenanceId");

                    b.ToTable("AIRCRAFT", (string)null);
                });

            modelBuilder.Entity("BaseStationReader.Entities.Api.Airline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("IATA")
                        .HasColumnType("TEXT")
                        .HasColumnName("IATA");

                    b.Property<string>("ICAO")
                        .HasColumnType("TEXT")
                        .HasColumnName("ICAO");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<int>("ProvenanceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProvenanceId");

                    b.HasKey("Id");

                    b.HasIndex("ICAO");

                    b.HasIndex("ProvenanceId");

                    b.ToTable("AIRLINE", (string)null);
                });

            modelBuilder.Entity("BaseStationReader.Entities.Api.AirlineCallsignPrefix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<int>("AirlineId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AirlineId");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("Prefix");

                    b.Property<int>("ProvenanceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProvenanceId");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.HasIndex("Prefix")
                        .IsUnique();

                    b.HasIndex("ProvenanceId");

                    b.ToTable("AIRLINE_CALLSIGN_PREFIX", (string)null);
                });

            modelBuilder.Entity("BaseStationReader.Entities.Api.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("IATA")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("IATA");

                    b.Property<string>("ICAO")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ICAO");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL")
                        .HasColumnName("Latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL")
                        .HasColumnName("Longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<int>("ProvenanceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProvenanceId");

                    b.HasKey("Id");

                    b.HasIndex("ProvenanceId");

                    b.ToTable("AIRPORT", (string)null);
                });

            modelBuilder.Entity("BaseStationReader.Entities.Api.ApiLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Endpoint");

                    b.Property<string>("Property")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Property");

                    b.Property<string>("PropertyValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("PropertyValue");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Service");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("DATETIME")
                        .HasColumnName("Timestamp");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Url");

                    b.HasKey("Id");

                    b.ToTable("API_LOG", (string)null);
                });

            modelBuilder.Entity("BaseStationReader.Entities.Api.ExcludedCallsign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Callsign");

                    b.HasKey("Id");

                    b.HasIndex("Callsign");

                    b.ToTable("EXCLUDED_CALLSIGN", (string)null);
                });

            modelBuilder.Entity("BaseStationReader.Entities.Api.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<int>("AirlineId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AirlineId");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Callsign");

                    b.Property<int>("DestinationAirportId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DestinationAirportId");

                    b.Property<string>("IATA")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("IATA");

                    b.Property<string>("ICAO")
                        .HasColumnType("TEXT")
                        .HasColumnName("ICAO");

                    b.Property<int>("OriginAirportId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OriginAirportId");

                    b.Property<int>("ProvenanceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProvenanceId");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.HasIndex("Callsign");

                    b.HasIndex("DestinationAirportId");

                    b.HasIndex("OriginAirportId");

                    b.HasIndex("ProvenanceId");

                    b.ToTable("FLIGHT", (string)null);
                });

            modelBuilder.Entity("BaseStationReader.Entities.Api.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<int>("ProvenanceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProvenanceId");

                    b.HasKey("Id");

                    b.HasIndex("ProvenanceId");

                    b.ToTable("MANUFACTURER", (string)null);
                });

            modelBuilder.Entity("BaseStationReader.Entities.Api.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("IATA")
                        .HasColumnType("TEXT")
                        .HasColumnName("IATA");

                    b.Property<string>("ICAO")
                        .HasColumnType("TEXT")
                        .HasColumnName("ICAO");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<int>("ProvenanceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProvenanceId");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("ProvenanceId");

                    b.ToTable("MODEL", (string)null);
                });

            modelBuilder.Entity("BaseStationReader.Entities.Api.Provenance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Licence")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Licence");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Source");

                    b.Property<string>("SourceDataset")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SourceDataset");

                    b.Property<string>("SourceRef")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SourceRef");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SourceUrl");

                    b.Property<string>("SourceVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SourceVersion");

                    b.HasKey("Id");

                    b.HasIndex("SourceRef")
                        .IsUnique();

                    b.ToTable("PROVENANCE", (string)null);
                });

            modelBuilder.Entity("BaseStationReader.Entities.Api.Sighting", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<int>("AircraftId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AircraftId");

                    b.Property<int>("AirlineId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AirlineId");

                    b.Property<int?>("FlightId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FlightId");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("DATETIME")
                        .HasColumnName("Timestamp");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("AirlineId");

                    b.HasIndex("FlightId");

                    b.ToTable((string)null);

                    b.ToView("SIGHTING", (string)null);
                });

            modelBuilder.Entity("BaseStationReader.Entities.Equipment.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<int>("EquipmentTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EquipmentTypeId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EQUIPMENT", (string)null);
                });

            modelBuilder.Entity("BaseStationReader.Entities.Equipment.EquipmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EQUIPMENT_TYPE", (string)null);
                });

            modelBuilder.Entity("BaseStationReader.Entities.Equipment.SessionEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EquipmentId");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SessionId");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("SessionId", "EquipmentId")
                        .IsUnique();

                    b.ToTable("SESSION_EQUIPMENT", (string)null);
                });

            modelBuilder.Entity("BaseStationReader.Entities.History.PositionDensitySnapshotCellEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Count");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL")
                        .HasColumnName("Latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL")
                        .HasColumnName("Longitude");

                    b.Property<int>("PositionDensitySnapshotId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PositionDensitySnapshotId");

                    b.HasKey("Id");

                    b.HasIndex("PositionDensitySnapshotId", "Latitude", "Longitude")
                        .IsUnique();

                    b.ToTable("POSITION_DENSITY_SNAPSHOT_CELL", null, t =>
                        {
                            t.HasCheckConstraint("CK_POSITION_DENSITY_SNAPSHOT_CELL_Count", "Count > 0");
                        });
                });

            modelBuilder.Entity("BaseStationReader.Entities.History.PositionDensitySnapshotEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("DATETIME")
                        .HasColumnName("CapturedAtUtc");

                    b.Property<int>("MaximumBinCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MaximumBinCount");

                    b.Property<double>("MaximumLatitude")
                        .HasColumnType("REAL")
                        .HasColumnName("MaximumLatitude");

                    b.Property<double>("MaximumLongitude")
                        .HasColumnType("REAL")
                        .HasColumnName("MaximumLongitude");

                    b.Property<double>("MinimumLatitude")
                        .HasColumnType("REAL")
                        .HasColumnName("MinimumLatitude");

                    b.Property<double>("MinimumLongitude")
                        .HasColumnType("REAL")
                        .HasColumnName("MinimumLongitude");

                    b.Property<int>("PositionCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PositionCount");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SessionId");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "CapturedAtUtc");

                    b.ToTable("POSITION_DENSITY_SNAPSHOT", null, t =>
                        {
                            t.HasCheckConstraint("CK_POSITION_DENSITY_SNAPSHOT_LatitudeBounds", "MaximumLatitude >= MinimumLatitude");

                            t.HasCheckConstraint("CK_POSITION_DENSITY_SNAPSHOT_LongitudeBounds", "MaximumLongitude >= MinimumLongitude");

                            t.HasCheckConstraint("CK_POSITION_DENSITY_SNAPSHOT_MaximumBinCount", "MaximumBinCount >= 0");

                            t.HasCheckConstraint("CK_POSITION_DENSITY_SNAPSHOT_PositionCount", "PositionCount >= 0");
                        });
                });

            modelBuilder.Entity("BaseStationReader.Entities.Tracking.AircraftNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("TEXT")
                        .HasColumnName("Address");

                    b.Property<DateTime>("Date")
                        .HasColumnType("DATETIME")
                        .HasColumnName("Date");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("NoteText");

                    b.HasKey("Id");

                    b.HasIndex("Address", "Date");

                    b.ToTable("AIRCRAFT_NOTE", (string)null);
                });

            modelBuilder.Entity("BaseStationReader.Entities.Tracking.AircraftPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Address");

                    b.Property<int>("AircraftId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Altitude")
                        .HasColumnType("REAL")
                        .HasColumnName("Altitude");

                    b.Property<double?>("Distance")
                        .HasColumnType("REAL")
                        .HasColumnName("Distance");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("REAL")
                        .HasColumnName("Latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("REAL")
                        .HasColumnName("Longitude");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("DATETIME")
                        .HasColumnName("Timestamp");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId", "Timestamp");

                    b.ToTable("POSITION", (string)null);
                });

            modelBuilder.Entity("BaseStationReader.Entities.Tracking.ExcludedAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Address");

                    b.HasKey("Id");

                    b.HasIndex("Address");

                    b.ToTable("EXCLUDED_ADDRESS", (string)null);
                });

            modelBuilder.Entity("BaseStationReader.Entities.Tracking.ObservationSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Host");

                    b.Property<string>("IncludedBehaviours")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("IncludedBehaviours");

                    b.Property<int?>("MaximumAltitude")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MaximumAltitude");

                    b.Property<int?>("MaximumDistance")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MaximumDistance");

                    b.Property<int?>("MinimumAltitude")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MinimumAltitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("Notes");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Port");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ProfileName");

                    b.Property<int?>("ReceiverElevation")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ReceiverElevation");

                    b.Property<double?>("ReceiverLatitude")
                        .HasColumnType("REAL")
                        .HasColumnName("ReceiverLatitude");

                    b.Property<double?>("ReceiverLongitude")
                        .HasColumnType("REAL")
                        .HasColumnName("ReceiverLongitude");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("DATETIME")
                        .HasColumnName("StartedAtUtc");

                    b.HasKey("Id");

                    b.HasIndex("StartedAtUtc");

                    b.ToTable("SESSION", (string)null);
                });

            modelBuilder.Entity("BaseStationReader.Entities.Tracking.TrackedAircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Address");

                    b.Property<decimal?>("Altitude")
                        .HasColumnType("REAL")
                        .HasColumnName("Altitude");

                    b.Property<string>("Callsign")
                        .HasColumnType("TEXT")
                        .HasColumnName("Callsign");

                    b.Property<double?>("Distance")
                        .HasColumnType("REAL")
                        .HasColumnName("Distance");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("DATETIME")
                        .HasColumnName("FirstSeen");

                    b.Property<decimal?>("GroundSpeed")
                        .HasColumnType("REAL")
                        .HasColumnName("GroundSpeed");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("DATETIME")
                        .HasColumnName("LastSeen");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("REAL")
                        .HasColumnName("Latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("REAL")
                        .HasColumnName("Longitude");

                    b.Property<int>("Messages")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Messages");

                    b.Property<int?>("SessionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SessionId");

                    b.Property<string>("Squawk")
                        .HasColumnType("TEXT")
                        .HasColumnName("Squawk");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Status");

                    b.Property<decimal?>("Track")
                        .HasColumnType("REAL")
                        .HasColumnName("Track");

                    b.Property<decimal?>("VerticalRate")
                        .HasColumnType("REAL")
                        .HasColumnName("VerticalRate");

                    b.HasKey("Id");

                    b.HasIndex("Address");

                    b.HasIndex("Callsign");

                    b.HasIndex("FirstSeen");

                    b.HasIndex("LastSeen");

                    b.HasIndex("SessionId");

                    b.HasIndex("Status");

                    b.ToTable("TRACKED_AIRCRAFT", (string)null);
                });

            modelBuilder.Entity("BaseStationReader.Entities.Api.Aircraft", b =>
                {
                    b.HasOne("BaseStationReader.Entities.Api.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseStationReader.Entities.Api.Provenance", "Provenance")
                        .WithMany()
                        .HasForeignKey("ProvenanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("Provenance");
                });

            modelBuilder.Entity("BaseStationReader.Entities.Api.Airline", b =>
                {
                    b.HasOne("BaseStationReader.Entities.Api.Provenance", "Provenance")
                        .WithMany()
                        .HasForeignKey("ProvenanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provenance");
                });

            modelBuilder.Entity("BaseStationReader.Entities.Api.AirlineCallsignPrefix", b =>
                {
                    b.HasOne("BaseStationReader.Entities.Api.Airline", "Airline")
                        .WithMany()
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseStationReader.Entities.Api.Provenance", "Provenance")
                        .WithMany()
                        .HasForeignKey("ProvenanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Airline");

                    b.Navigation("Provenance");
                });

            modelBuilder.Entity("BaseStationReader.Entities.Api.Airport", b =>
                {
                    b.HasOne("BaseStationReader.Entities.Api.Provenance", "Provenance")
                        .WithMany()
                        .HasForeignKey("ProvenanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provenance");
                });

            modelBuilder.Entity("BaseStationReader.Entities.Api.Flight", b =>
                {
                    b.HasOne("BaseStationReader.Entities.Api.Airline", "Airline")
                        .WithMany()
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseStationReader.Entities.Api.Airport", "DestinationAirport")
                        .WithMany()
                        .HasForeignKey("DestinationAirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseStationReader.Entities.Api.Airport", "OriginAirport")
                        .WithMany()
                        .HasForeignKey("OriginAirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseStationReader.Entities.Api.Provenance", "Provenance")
                        .WithMany()
                        .HasForeignKey("ProvenanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Airline");

                    b.Navigation("DestinationAirport");

                    b.Navigation("OriginAirport");

                    b.Navigation("Provenance");
                });

            modelBuilder.Entity("BaseStationReader.Entities.Api.Manufacturer", b =>
                {
                    b.HasOne("BaseStationReader.Entities.Api.Provenance", "Provenance")
                        .WithMany()
                        .HasForeignKey("ProvenanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provenance");
                });

            modelBuilder.Entity("BaseStationReader.Entities.Api.Model", b =>
                {
                    b.HasOne("BaseStationReader.Entities.Api.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseStationReader.Entities.Api.Provenance", "Provenance")
                        .WithMany()
                        .HasForeignKey("ProvenanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");

                    b.Navigation("Provenance");
                });

            modelBuilder.Entity("BaseStationReader.Entities.Api.Sighting", b =>
                {
                    b.HasOne("BaseStationReader.Entities.Api.Aircraft", "Aircraft")
                        .WithMany()
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseStationReader.Entities.Api.Airline", "Airline")
                        .WithMany()
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseStationReader.Entities.Api.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId");

                    b.Navigation("Aircraft");

                    b.Navigation("Airline");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("BaseStationReader.Entities.Equipment.Equipment", b =>
                {
                    b.HasOne("BaseStationReader.Entities.Equipment.EquipmentType", "EquipmentType")
                        .WithMany("Equipment")
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EquipmentType");
                });

            modelBuilder.Entity("BaseStationReader.Entities.Equipment.SessionEquipment", b =>
                {
                    b.HasOne("BaseStationReader.Entities.Equipment.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseStationReader.Entities.Tracking.ObservationSession", "Session")
                        .WithMany("SessionEquipment")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("BaseStationReader.Entities.History.PositionDensitySnapshotCellEntity", b =>
                {
                    b.HasOne("BaseStationReader.Entities.History.PositionDensitySnapshotEntity", "PositionDensitySnapshot")
                        .WithMany("Cells")
                        .HasForeignKey("PositionDensitySnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PositionDensitySnapshot");
                });

            modelBuilder.Entity("BaseStationReader.Entities.History.PositionDensitySnapshotEntity", b =>
                {
                    b.HasOne("BaseStationReader.Entities.Tracking.ObservationSession", "Session")
                        .WithMany("PositionDensitySnapshots")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("BaseStationReader.Entities.Tracking.AircraftPosition", b =>
                {
                    b.HasOne("BaseStationReader.Entities.Tracking.TrackedAircraft", "Aircraft")
                        .WithMany()
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aircraft");
                });

            modelBuilder.Entity("BaseStationReader.Entities.Tracking.TrackedAircraft", b =>
                {
                    b.HasOne("BaseStationReader.Entities.Tracking.ObservationSession", "Session")
                        .WithMany("TrackedAircraft")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Session");
                });

            modelBuilder.Entity("BaseStationReader.Entities.Equipment.EquipmentType", b =>
                {
                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("BaseStationReader.Entities.History.PositionDensitySnapshotEntity", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("BaseStationReader.Entities.Tracking.ObservationSession", b =>
                {
                    b.Navigation("PositionDensitySnapshots");

                    b.Navigation("SessionEquipment");

                    b.Navigation("TrackedAircraft");
                });
#pragma warning restore 612, 618
        }
    }
}
