// <auto-generated />
using System;
using BaseStationReader.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaseStationReader.Data.Migrations
{
    [DbContext(typeof(BaseStationReaderDbContext))]
    partial class BaseStationReaderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("BaseStationReader.Entities.Api.Aircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Address");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Age");

                    b.Property<int?>("Manufactured")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Manufactured");

                    b.Property<int>("ModelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProvenanceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProvenanceId");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Registration");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.HasIndex("ProvenanceId");

                    b.ToTable("AIRCRAFT", (string)null);
                });

            modelBuilder.Entity("BaseStationReader.Entities.Api.Airline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("IATA")
                        .HasColumnType("TEXT")
                        .HasColumnName("IATA");

                    b.Property<string>("ICAO")
                        .HasColumnType("TEXT")
                        .HasColumnName("ICAO");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<int>("ProvenanceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProvenanceId");

                    b.HasKey("Id");

                    b.HasIndex("ProvenanceId");

                    b.ToTable("AIRLINE", (string)null);
                });

            modelBuilder.Entity("BaseStationReader.Entities.Api.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("IATA")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("IATA");

                    b.Property<string>("ICAO")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ICAO");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL")
                        .HasColumnName("Latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL")
                        .HasColumnName("Longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<int>("ProvenanceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProvenanceId");

                    b.HasKey("Id");

                    b.HasIndex("ProvenanceId");

                    b.ToTable("AIRPORT", (string)null);
                });

            modelBuilder.Entity("BaseStationReader.Entities.Api.ApiLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Endpoint");

                    b.Property<string>("Property")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Property");

                    b.Property<string>("PropertyValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("PropertyValue");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Service");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("DATETIME")
                        .HasColumnName("Timestamp");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Url");

                    b.HasKey("Id");

                    b.ToTable("API_LOG", (string)null);
                });

            modelBuilder.Entity("BaseStationReader.Entities.Api.ExcludedCallsign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Callsign");

                    b.HasKey("Id");

                    b.ToTable("EXCLUDED_CALLSIGN", (string)null);
                });

            modelBuilder.Entity("BaseStationReader.Entities.Api.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<int>("AirlineId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AirlineId");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Callsign");

                    b.Property<int>("DestinationAirportId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DestinationAirportId");

                    b.Property<string>("IATA")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("IATA");

                    b.Property<string>("ICAO")
                        .HasColumnType("TEXT")
                        .HasColumnName("ICAO");

                    b.Property<int>("OriginAirportId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OriginAirportId");

                    b.Property<int>("ProvenanceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProvenanceId");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.HasIndex("DestinationAirportId");

                    b.HasIndex("OriginAirportId");

                    b.HasIndex("ProvenanceId");

                    b.ToTable("FLIGHT", (string)null);
                });

            modelBuilder.Entity("BaseStationReader.Entities.Api.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<int>("ProvenanceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProvenanceId");

                    b.HasKey("Id");

                    b.HasIndex("ProvenanceId");

                    b.ToTable("MANUFACTURER", (string)null);
                });

            modelBuilder.Entity("BaseStationReader.Entities.Api.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("IATA")
                        .HasColumnType("TEXT")
                        .HasColumnName("IATA");

                    b.Property<string>("ICAO")
                        .HasColumnType("TEXT")
                        .HasColumnName("ICAO");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<int>("ProvenanceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProvenanceId");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("ProvenanceId");

                    b.ToTable("MODEL", (string)null);
                });

            modelBuilder.Entity("BaseStationReader.Entities.Api.Provenance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Licence")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Licence");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Source");

                    b.Property<string>("SourceDataset")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SourceDataset");

                    b.Property<string>("SourceRef")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SourceRef");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SourceUrl");

                    b.Property<string>("SourceVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SourceVersion");

                    b.HasKey("Id");

                    b.HasIndex("SourceRef")
                        .IsUnique();

                    b.ToTable("PROVENANCE", (string)null);
                });

            modelBuilder.Entity("BaseStationReader.Entities.Api.Sighting", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<int>("AircraftId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AircraftId");

                    b.Property<int>("FlightId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FlightId");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("DATETIME")
                        .HasColumnName("Timestamp");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("FlightId");

                    b.ToView("SIGHTING", (string)null);
                });

            modelBuilder.Entity("BaseStationReader.Entities.Tracking.AircraftPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Address");

                    b.Property<int>("AircraftId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Altitude")
                        .HasColumnType("REAL")
                        .HasColumnName("Altitude");

                    b.Property<double?>("Distance")
                        .HasColumnType("REAL")
                        .HasColumnName("Distance");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("REAL")
                        .HasColumnName("Latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("REAL")
                        .HasColumnName("Longitude");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("DATETIME")
                        .HasColumnName("Timestamp");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId", "Timestamp");

                    b.ToTable("POSITION", (string)null);
                });

            modelBuilder.Entity("BaseStationReader.Entities.Tracking.ExcludedAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Address");

                    b.HasKey("Id");

                    b.ToTable("EXCLUDED_ADDRESS", (string)null);
                });

            modelBuilder.Entity("BaseStationReader.Entities.Tracking.ObservationSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Host");

                    b.Property<string>("IncludedBehaviours")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("IncludedBehaviours");

                    b.Property<int?>("MaximumAltitude")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MaximumAltitude");

                    b.Property<int?>("MaximumDistance")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MaximumDistance");

                    b.Property<int?>("MinimumAltitude")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MinimumAltitude");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("Notes");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Port");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ProfileName");

                    b.Property<int?>("ReceiverElevation")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ReceiverElevation");

                    b.Property<double?>("ReceiverLatitude")
                        .HasColumnType("REAL")
                        .HasColumnName("ReceiverLatitude");

                    b.Property<double?>("ReceiverLongitude")
                        .HasColumnType("REAL")
                        .HasColumnName("ReceiverLongitude");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("DATETIME")
                        .HasColumnName("StartedAtUtc");

                    b.HasKey("Id");

                    b.HasIndex("StartedAtUtc");

                    b.ToTable("SESSION", (string)null);
                });

            modelBuilder.Entity("BaseStationReader.Entities.Tracking.TrackedAircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Address");

                    b.Property<decimal?>("Altitude")
                        .HasColumnType("REAL")
                        .HasColumnName("Altitude");

                    b.Property<string>("Callsign")
                        .HasColumnType("TEXT")
                        .HasColumnName("Callsign");

                    b.Property<double?>("Distance")
                        .HasColumnType("REAL")
                        .HasColumnName("Distance");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("DATETIME")
                        .HasColumnName("FirstSeen");

                    b.Property<decimal?>("GroundSpeed")
                        .HasColumnType("REAL")
                        .HasColumnName("GroundSpeed");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("DATETIME")
                        .HasColumnName("LastSeen");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("REAL")
                        .HasColumnName("Latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("REAL")
                        .HasColumnName("Longitude");

                    b.Property<int>("Messages")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Messages");

                    b.Property<int?>("SessionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SessionId");

                    b.Property<string>("Squawk")
                        .HasColumnType("TEXT")
                        .HasColumnName("Squawk");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Status");

                    b.Property<decimal?>("Track")
                        .HasColumnType("REAL")
                        .HasColumnName("Track");

                    b.Property<decimal?>("VerticalRate")
                        .HasColumnType("REAL")
                        .HasColumnName("VerticalRate");

                    b.HasKey("Id");

                    b.HasIndex("Address");

                    b.HasIndex("Callsign");

                    b.HasIndex("FirstSeen");

                    b.HasIndex("LastSeen");

                    b.HasIndex("SessionId");

                    b.HasIndex("Status");

                    b.ToTable("TRACKED_AIRCRAFT", (string)null);
                });

            modelBuilder.Entity("BaseStationReader.Entities.Api.Aircraft", b =>
                {
                    b.HasOne("BaseStationReader.Entities.Api.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseStationReader.Entities.Api.Provenance", "Provenance")
                        .WithMany()
                        .HasForeignKey("ProvenanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("Provenance");
                });

            modelBuilder.Entity("BaseStationReader.Entities.Api.Airline", b =>
                {
                    b.HasOne("BaseStationReader.Entities.Api.Provenance", "Provenance")
                        .WithMany()
                        .HasForeignKey("ProvenanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provenance");
                });

            modelBuilder.Entity("BaseStationReader.Entities.Api.Airport", b =>
                {
                    b.HasOne("BaseStationReader.Entities.Api.Provenance", "Provenance")
                        .WithMany()
                        .HasForeignKey("ProvenanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provenance");
                });

            modelBuilder.Entity("BaseStationReader.Entities.Api.Flight", b =>
                {
                    b.HasOne("BaseStationReader.Entities.Api.Airline", "Airline")
                        .WithMany()
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseStationReader.Entities.Api.Airport", "DestinationAirport")
                        .WithMany()
                        .HasForeignKey("DestinationAirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseStationReader.Entities.Api.Airport", "OriginAirport")
                        .WithMany()
                        .HasForeignKey("OriginAirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseStationReader.Entities.Api.Provenance", "Provenance")
                        .WithMany()
                        .HasForeignKey("ProvenanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Airline");

                    b.Navigation("DestinationAirport");

                    b.Navigation("OriginAirport");

                    b.Navigation("Provenance");
                });

            modelBuilder.Entity("BaseStationReader.Entities.Api.Manufacturer", b =>
                {
                    b.HasOne("BaseStationReader.Entities.Api.Provenance", "Provenance")
                        .WithMany()
                        .HasForeignKey("ProvenanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provenance");
                });

            modelBuilder.Entity("BaseStationReader.Entities.Api.Model", b =>
                {
                    b.HasOne("BaseStationReader.Entities.Api.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseStationReader.Entities.Api.Provenance", "Provenance")
                        .WithMany()
                        .HasForeignKey("ProvenanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");

                    b.Navigation("Provenance");
                });

            modelBuilder.Entity("BaseStationReader.Entities.Api.Sighting", b =>
                {
                    b.HasOne("BaseStationReader.Entities.Api.Aircraft", "Aircraft")
                        .WithMany()
                        .HasForeignKey("AircraftId")
                        .IsRequired();

                    b.HasOne("BaseStationReader.Entities.Api.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .IsRequired();

                    b.Navigation("Aircraft");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("BaseStationReader.Entities.Tracking.AircraftPosition", b =>
                {
                    b.HasOne("BaseStationReader.Entities.Tracking.TrackedAircraft", "Aircraft")
                        .WithMany()
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aircraft");
                });

            modelBuilder.Entity("BaseStationReader.Entities.Tracking.TrackedAircraft", b =>
                {
                    b.HasOne("BaseStationReader.Entities.Tracking.ObservationSession", "Session")
                        .WithMany("TrackedAircraft")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Session");
                });

            modelBuilder.Entity("BaseStationReader.Entities.Tracking.ObservationSession", b =>
                {
                    b.Navigation("TrackedAircraft");
                });
#pragma warning restore 612, 618
        }
    }
}
